# Generated by Django 5.1.1 on 2024-09-25 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=15, unique=True)),
                ('car_model', models.CharField(max_length=30)),
                ('car_color', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=10)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cimak_app.car')),
            ],
            options={
                'permissions': [('can_view_manager', 'يمكنه عرض صفحة الإدارة'), ('can_edit_data_entry', 'يمكنه إدخال البيانات'), ('can_view_accepted_bookings', 'يمكنه عرض الحجوزات المقبولة')],
            },
        ),
    ]
